version: "2"
services:
 web:
  build: .
  command: npm run debug
  volumes:
   - ./src:/app/src
   - ./config:/app/config
   - ./node_modules:/app/node_modules
  ports:
   - "3000:3000"
   - "9229:9229"
  depends_on:
   - "mongo"
  stdin_open: true
  tty: true
 mongo:
  image: mongo